services:
    postgres:
        image: postgres:14.2-alpine
        environment:
            - POSTGRES_PASSWORD=supersecurepassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /var/lib/postgresql/data/pgdata
    boolean:
        build: .
        restart: always
        links:
            - postgres
